version: "2.3"

services:
  controller:
    image: prodoai/plz_controller:timestamp_${BUILD_TIMESTAMP}
    ports:
      - ${PORT:-5123}:80
    environment:
      CREATE_AWS_RESOURCES: "yes"
      CONFIGURATION: |
        config = { include "/root/config.json" }
        include "/root/server.conf"
        include "/root/docker.conf"
        log_level = ${LOG_LEVEL:-DEBUG}
    volumes:
      - ${SECRETS_DIR}/config.json:/root/config.json:ro
      - ./docker.conf:/root/docker.conf:ro
      - ./localserver.conf:/root/server.conf:ro
      - ${CACHE_DIR}/controller:/data
      - ${CACHE_DIR}/results:/data/results
      - ${HOME}/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:4
    entrypoint: redis-server --save 2 1 --loglevel warning
    volumes:
      - ${CACHE_DIR}/redis_data:/data
